# Generated by Django 6.0.2 on 2026-02-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50, unique=True, verbose_name='Торговая пара')),
                ('bid_price', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Цена покупки')),
                ('ask_price', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Цена продажи')),
                ('last_price', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Последняя цена')),
                ('prev_price_24h', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Цена 24ч назад')),
                ('price_24h_pcnt', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Изменение 24ч (%)')),
                ('high_price_24h', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Максимум 24ч')),
                ('low_price_24h', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Минимум 24ч')),
                ('volume_24h', models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True, verbose_name='Объем 24ч')),
                ('turnover_24h', models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True, verbose_name='Оборот 24ч')),
                ('usd_index_price', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='USD индекс')),
                ('category', models.CharField(default='spot', max_length=20, verbose_name='Категория')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Тикер',
                'verbose_name_plural': 'Тикеры',
                'ordering': ['-volume_24h'],
            },
        ),
    ]
